- name: Check if homebrew in already installed
  shell: "which brew > /dev/null 2>&1; echo $?"
  register: brew_installed

- name: Install homebrew
  include: install_brew.yml
  when: (not brew_installed.stdout)
