- name: Check if homebrew is already installed
  shell: which brew
  register: brew_installed
  environment:
    PATH: "/usr/local/bin:/usr/bin"

- name: Install homebrew
  include: install_brew.yml
  when: brew_installed.rc != 0

- name: Upgrade any already-installed formulae
  shell: /usr/local/bin/brew upgrade --all

- include: install_apps.yml

- name: Brew cleanup
  shell: /usr/local/bin/brew cleanup
