cask_tools:
  - vagrant

cask_applications:
  - eclipse-jee
  - firefox
  - google-chrome
  - iterm2
  - java
  - mysqlworkbench
  - skype
  - slack
  - spotify
  - transmission
  - virtualbox
  - vlc
