- name: Check if homebrew cask is already installed
  shell: brew info brew-cask
  register: brew_cask_installed
  environment:
    PATH: "/usr/local/bin:/usr/bin"

- name: Install homebrew cask
  include: install_cask.yml
  when: brew_cask_installed.rc != 0

- include: install_apps.yml
